name: Build iOS

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.0"

      - run: flutter pub get

      - run: |
          cd ios
          pod install

      - run: flutter build ios --release --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/
